# permissions for end users to edit remoteassemblages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteassemblage-editor-role
rules:
- apiGroups:
  - fleet.squaremo.dev
  resources:
  - remoteassemblages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.squaremo.dev
  resources:
  - remoteassemblages/status
  verbs:
  - get
