# permissions for end users to view remoteassemblages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteassemblage-viewer-role
rules:
- apiGroups:
  - fleet.squaremo.dev
  resources:
  - remoteassemblages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.squaremo.dev
  resources:
  - remoteassemblages/status
  verbs:
  - get
