---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-api
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./configs/cluster-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

