---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleeet-control
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-api
  interval: 1m0s
  path: ./configs/fleeet-control/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

